### ISSUE TITLE
Chapter03/blog elasticsearch config

### ISSUE THREAD

**Issue by llitfkitfk** [PacktPublishing/Spring-Boot-2.0-Projects#1]
```
spring.data.elasticsearch.cluster-name=docker-cluster
spring.data.elasticsearch.cluster-nodes=elasticsearch:9300 
spring.data.elasticsearch.repositories.enabled=true
```

if using elasticsearch in docker 
https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html

**Comment by shazin** [comment]
Docker is explained only at Chapter 06. Adding docker to a project in Chapter 03 is premature and will confuse and overwhelm readers.

**Comment by boonkuaeb** [comment]
Hi All,
It works for me.

**1. Pull Elasticsearch Images**
`docker pull docker.elastic.co/elasticsearch/elasticsearch:6.5.1    `

**2. Create elasticserch container**
` docker run -d --name elasticsearch_bloggest -p 9200:9200 -p 9300:9300 -e "http.host=0.0.0.0" -e "transport.host=0.0.0.0" docker.elastic.co/elasticsearch/elasticsearch:6.5.1`

**3. Edit application.properties file**
`spring.data.elasticsearch.cluster-nodes=localhost:9300`
`spring.data.elasticsearch.cluster-name=docker-cluster`
