### ISSUE TITLE
PageRequest constructors have been deprecated

### ISSUE THREAD

**Issue by tifuseini** [PacktPublishing/Spring-Boot-2.0-Projects#19]
Article Controller

java: constructor PageRequest in class org.springframework.data.domain.PageRequest cannot be applied to given types;
  required: int,int,org.springframework.data.domain.Sort
  found:    int,int
  reason: actual and formal argument lists differ in length

**Comment by shazin** [comment]
Hi @tifuseini, Thanks for mentioning about this. This is now fixed in master. Please pull latest source code from master.
